output_dir: 'results_core50/281024'
batch_size: 1024
epochs: 50
num_experiments: 20
device: 'cuda:1'
experiment_type: 'class' # mixed, cbp or bp (used only to name the directory – specify backpropagation type in tge individual model dictionaries)
dataset: 'custom'  # 
num_classes: 50 # 50 for core50
batch_size: 1048

# Custom dataset parameters
custom_dataset:
  data_path: 'data/core50_features/full.npy'
  labels_path: 'data/core50_features/full_labels.npy'
  vector_len: 2048

# EMNIST dataset parameters (no additional parameters needed)

# Neural Network configuration
feature_classifier: 
  input_size: 2048
  hidden1: 512
  hidden2: 256
  num_classes: 50
  cbp: true

generator:
    alpha: 10.
    num_classes: 50
    latent_dim: 10
    cbp: false
    encoder_config:
        input_size: 2048
        hidden1: 128
        hidden2: 128
    decoder_config:
        output_size: 2048
        hidden1: 128
        hidden2: 128