output_dir: 'results_core50'
batch_size: 1024
epochs: 100
num_experiments: 1
device: 'cuda:0'
experiment_type: 'cbp' # mixed, class, cbp or bp (used only to name the directory – specify backpropagation type in tge individual model dictionaries)
dataset: 'custom'  # 
num_classes: 50 # 50 for core50
softmax_filter: 0.0

# Custom dataset parameters
custom_dataset:
  data_path: '/cluster/home/mateuwa/plasticity-greplay/data/core50_features/full.npy'
  labels_path: '/cluster/home/mateuwa/plasticity-greplay/data/core50_features/full_labels.npy'
  vector_len: 2048

# EMNIST dataset parameters (no additional parameters needed)

# Neural Network configuration
feature_classifier: 
  input_size: 2048
  hidden1: 512
  hidden2: 256
  num_classes: 50
  cbp: true

generator:
    alpha: 10.
    num_classes: 50
    latent_dim: 10
    cbp: true
    encoder_config:
        input_size: 2048
        hidden1: 128
        hidden2: 128
    decoder_config:
        output_size: 2048
        hidden1: 128
        hidden2: 128

cbp_config:
  replacement_rate: 0.0001 # 10e-4 gets interpreted as a string
  maturity_threshold: 100
  decay_rate: 0.0 #decay rate >0 seems to break the code

